### ISSUE TITLE
macOS does not have a `realpath` shell command by default

### ISSUE THREAD

**Issue by whereswaldon** [alexherbo2/connect.kak#1]
I'm not sure what your preferred way to handle this would be, but the default userspace tools for macOS don't have `realpath`. It seems to me that there are a few easy ways forward:
- Note that you need it in the README (`brew install coreutils`).
- Define a [fallback bash function](https://flummox-engineering.blogspot.com/2014/06/getting-absolute-path-in-bash-in-osx.html) that does the same thing within `connect.kak`.
- Refactor to not use `realpath` in the script.
- State that macOS us unsupported (maybe a bit extreme)

I'd be happy to take care of this myself if anyone has a preference as to which of the above is the right way to handle this.

**Comment by alexherbo2** [comment]
@whereswaldon Sorry for the late answer. :confused:
