### ISSUE TITLE
Connect-terminal and related not working on OSX with iterm2

### ISSUE THREAD

**Issue by tbdcit** [alexherbo2/connect.kak#10]
I am having some issues getting kakoune-connect to work on mac OSX in iterm2. When running `connect-terminal` a new terminal tab appears breifly and then closes right away. I have aliased `terminal` to `iterm-terminal-tab` and running commands like `terminal bash` work as expected. I am not really sure how I can debug this issue any further. I have no problems on my linux box using the exact same setup (but in a different terminal emulator). 

Any suggestions in regards to debuging or fixing this issue would be very much appreciated. Relevant parts of my `kakrc` are bellow.

```
plug "alexherbo2/connect.kak" config %{
    # require-module connect-fzf
    require-module connect-rofi
    require-module connect-lf
    require-module connect-dolphin

    map global normal <c-t> ': connect-terminal<ret>'
}
```

```
hook global KakBegin .* %{
    evaluate-commands %sh{
        if [ "$TERM_PROGRAM" = "iTerm.app" ] && [ -z "$TMUX" ]; then
            echo "alias global terminal-tab iterm-terminal-tab"
            echo "alias global terminal iterm-terminal-tab"
        fi
    }
}
```

**Comment by alexherbo2** [comment]
I think it is because [`iterm.kak`] does not do a perfect forwarding.

[`iterm.kak`]: https://github.com/mawww/kakoune/blob/master/rc/windowing/iterm.kak

https://github.com/mawww/kakoune/pull/3293

Can you open an issue on Kakoune?

**Comment by alexherbo2** [comment]
Can you open an issue on Kakoune?

**Comment by alexherbo2** [comment]
I’m closing, as this issue is more addressed upstream.
