### ISSUE TITLE
Horizontal and Vertical Options

### ISSUE THREAD

**Issue by robertmeta** [alexherbo2/connect.kak#11]
I would love to be able to fire this off in a vertical or horizontal mode.

**Comment by alexherbo2** [comment]
connect.kak does not handle the windowing.
You should ask for [`tmux.kak`] or add a command to position the window.

`tmux-terminal-window` ⇒ `tmux-terminal-impl new-window %arg{@}`

[`tmux.kak`]: https://github.com/mawww/kakoune/blob/master/rc/windowing/tmux.kak

**Comment by robertmeta** [comment]
There exists ```tmux-terminal-vertical``` and ```tmux-terminal-horizontal```

**Comment by alexherbo2** [comment]
Do you see a nice way to make the `terminal` command in [`connect.kak`] configurable?

I’m not sure if it should be addressed here or upstream.

[`connect.kak`]: https://github.com/alexherbo2/connect.kak/blob/master/rc/connect.kak

**Comment by robertmeta** [comment]
Fair point, hmph... Let me consider it, if I come up with a good solution I will submit a PR.  I was hoping you would have a great notion!

**Comment by alexherbo2** [comment]
It could be nice to be able to tell `terminal` whether we want the newly created window.

Something like [Splitting containers] for setting the orientation could be nice for Kakoune.

[Splitting containers]: https://i3wm.org/docs/userguide.html#_splitting_containers

Maybe ask @occivink also.

**Comment by occivink** [comment]
At some point the idea of a `-split vertical|horizontal` parameter to `terminal` floated around, but it never really got anywhere. What you can do is simply change the `terminal` alias, like so
```
define-command connect-vertical %{ 
    alias global terminal tmux-terminal-vertical
    connect 
}
define-command connect-horizontal %{ 
    alias global terminal tmux-terminal-horizontal
    connect 
}
```
but it sucks a bit that it modifies the global configuration

**Comment by alexherbo2** [comment]
How about a `split` command setting an option, and the `terminal` implementations doing something with that option?

```
split (vertical|horizontal|toggle)
```

**Comment by robertmeta** [comment]
that would be amazing!

**Comment by alexherbo2** [comment]
@occivink Are you op to take care of that request?

**Comment by alexherbo2** [comment]
I’m closing, as this issue is more addressed upstream.

**Comment by alexherbo2** [comment]
@robertmeta [terminal-mode.kak]

[terminal-mode.kak]: https://github.com/alexherbo2/terminal-mode.kak
