### ISSUE TITLE
Close Terminal when kakoune session is killed

### ISSUE THREAD

**Issue by basbebe** [alexherbo2/connect.kak#17]
Would it be possible to quit the terminal when the kakoune client quits?

**Comment by alexherbo2** [comment]
A hook on `ClientClose`, killing by their PID launched apps.

https://github.com/mawww/kakoune/blob/master/doc/pages/hooks.asciidoc

**Comment by alexherbo2** [comment]
@occivink How to get the PID with `:terminal`?

**Comment by occivink** [comment]
The problem is that a `terminal` doesn't necessarily have a pid, for example a tmux or kitty pane. We _could_ have some kind of arbitrary identifier, along with a generic command to delete a terminal of the given id, but that gets somewhat complicated to abstract.

**Comment by alexherbo2** [comment]
@basbebe Maybe the new feature of connect.kak to open in the same terminal window can match your workflow.

**Example** – Open a connected shell and reattach with `edit`:

```
$ kak-connect → :connect-terminal → $ edit → Quit to return to your shell
```

**Example** – Open a connected shell and [lf]:

```
$ kak-connect → :connect-terminal → $ lf → Open a file → Quit to return to lf
```

**Example** – Open [lf] connected to the Kakoune session:

```
$ kak-connect → :lf
```

[lf]: https://github.com/gokcehan/lf

**Comment by basbebe** [comment]
Sounds great, I‘ll have a look at it!
