### ISSUE TITLE
Add ranger example in README

### ISSUE THREAD

**Issue by Delapouite** [alexherbo2/connect.kak#2]
Hello

Now that ranger is gone from the "official" rc in https://github.com/mawww/kakoune/commit/f38152d2f0e84e7db07d101e12993c274786549c I assume many newcomers will now try to use connect.kak

The README already have examples for lf and fzf which is great!
We could add another explicit line with a ranger example, this way new users will feel reassured that connect.kak also works with ranger if they don't know (yet) that lf is a ranger-like program.

**Comment by alexherbo2** [comment]
Yoo.  I replaced the [lf] example with [ranger].

[lf]: https://github.com/gokcehan/lf
[ranger]: https://ranger.github.io

**Comment by alexherbo2** [comment]
You are not very active these days.  Hope you’re good.
