### ISSUE TITLE
Send text to the connected terminal from kakoune

### ISSUE THREAD

**Issue by sucrecacao** [alexherbo2/connect.kak#20]
Would it be possible to send text from kakoune to the connected terminal ?

My initial idea is to use it as an interactive REPL to send the current selection + 'return' to ipython for e.g. But I think it can have a lot of other uses.

**Comment by alexherbo2** [comment]
https://github.com/mawww/kakoune/tree/master/rc/windowing/repl

**Comment by sucrecacao** [comment]
Wow didn't know this feature, that awsome thx !
