### ISSUE TITLE
Inconsistent focus handling

### ISSUE THREAD

**Issue by 6he** [alexherbo2/connect.kak#23]
Maybe this is intentional, but it seems to be inconsistent.

The edit command focuses the editor window.
The buffer command does not.

**Comment by alexherbo2** [comment]
If you can unify it elegantly, PRs are welcome. 😁

See [commands].

[commands]: https://github.com/alexherbo2/connect.kak/tree/master/rc/paths/commands

**Comment by 6he** [comment]
Ok :-) I will look into it.

**Comment by alexherbo2** [comment]
@6he I revisited the whole and fixed the issue at the same time.

**Comment by 6he** [comment]
I just saw it. Thanks a lot. This is a great plugin :-)
