### ISSUE TITLE
Document requirement to place `+<line>:<column>` before file name with `:edit`

### ISSUE THREAD

**Issue by EpocSquadron** [alexherbo2/connect.kak#36]
I came here to open an issue as to why I couldn't get my fuzzy-finder grep-in-files-with-preview command to work right. Then I found #31, adjusted my command and it suddenly worked. I had no idea this was supposed to come first. We should have some sort of warning in the docs that unlike the kakoune binary, where you put it matters for the `:edit` command.

Although, perhaps we should consider supporting either to avoid the surprising behaviour?

**Comment by alexherbo2** [comment]
I will take a look.  I’d like to keep the implementation simple and not slow.

If you have a suggestion for the [`:edit`] command, you can open a PR or paste a gist below.

[`:edit`]: https://github.com/alexherbo2/connect.kak/blob/master/rc/connect/commands/:edit

**Comment by EpocSquadron** [comment]
No suggestion in particular. I don't know the internals and how you got to where you are with it. Documentation should be enough.
