### ISSUE TITLE
FZF Plugin fails in latest connect.kak without configuration changes

### ISSUE THREAD

**Issue by qstearns** [alexherbo2/connect.kak#41]
After switching the default command to popup in https://github.com/alexherbo2/connect.kak/commit/036f0bfaf7ef5bdda89ccaeb7473b8c5a49befe8, the fzf plugin fails by default without adding a popup command with:

```
https://github.com/alexherbo2/connect.kak/commit/036f0bfaf7ef5bdda89ccaeb7473b8c5a49befe8
```

I see that we're blocked on some upstream changes in order to get tmux popups working (https://github.com/mawww/kakoune/issues/3878 and https://github.com/tmux/tmux/issues/2475), but I was wondering if you had any recommendations about how to address in the mean time.

Thank you for the amazing plugin.

**Comment by alexherbo2** [comment]
Hi @qstearns,

I’ve added an entry in the [FAQ – I don’t have a popup command].

[FAQ – I don’t have a popup command]: https://github.com/alexherbo2/connect.kak/blob/master/docs/faq.md#i-dont-have-a-popup-command

**Comment by qstearns** [comment]
Ah excellent! Thanks for the input -- very much looking forward to the popup functionality in tmux.
