### ISSUE TITLE
:cat not working

### ISSUE THREAD

**Issue by basbebe** [alexherbo2/connect.kak#45]
I'm using macOS 11.1 and Kakoune 2020.09.01

when I'm doing `:cat` from a connected terminal I have this in the debug buffer:

```console
error running command ''evaluate-commands' '-try-client' 'client0' 'write' '-method' 'overwrite' 'buffer.fifo' 
': 1:1: 'evaluate-commands' 1:1: 'write' unknown option '-method'
```

The Terminal is suspended / waits for output but nothing happens.

**Comment by alexherbo2** [comment]
Your Kakoune version is too old.

https://github.com/mawww/kakoune/issues/3827
