### ISSUE TITLE
make kak-shell scriptable

### ISSUE THREAD

**Issue by basbebe** [alexherbo2/connect.kak#52]
I would love to ahve the possibility to make `kak-shell` scriptable.

What do I mean?

E.g. I have a fish function that does:

- open a new kitty tab at a given folder
- create a new kakoune ide session with the folders' name

At this point, when I want to leverage all that awesome `connect.kak` functionality, I would have to more or less re-write `kak-shell` in the fish function:

instantiate session in the background, wait, connect client, issue connect-detach, sh connect.sh, open ide.

What I would like to do would be:
`kak-shell -n sessionname` and that would open a new kak-shell with a new session 'sessionname'.

**Comment by alexherbo2** [comment]
In short, you want to connect to a session from the command-line without a prompt?

**Comment by basbebe** [comment]
yes.
Or create that session if it doesn't exist yet.

**Comment by alexherbo2** [comment]
How about:

```
kak-shell [session] [commands]
```

**Example** – Without a prompt:

``` sh
kak-shell kanto :attach
```

**Example** – With a prompt:

``` sh
kak-shell '' :attach
```

**Comment by basbebe** [comment]
would be great I think

**Comment by alexherbo2** [comment]
@basbebe Tell me if the UI is good.  The prompt thing was inspired by [3mux].  But now we can connect to a session without a prompt with:

```
kak-shell [session] [commands]
```

To be prompted _and_ execute a command, we use an empty session:

``` sh
kak-shell '' :attach
```

Which can be surprising in terms of UI.

[3mux]: https://github.com/aaronjanse/3mux

**Comment by basbebe** [comment]
I like the functionality but I also think the UI isn't intuitive.
`kak-shell :attach` now ends in an infinite loop.

I personally would prefer flags like `kak-shell -s kanto :attach` which wouldn't break `kak-shell :attach`.
