### ISSUE TITLE
No Type entry in kakoune-connect.desktop

### ISSUE THREAD

**Issue by useredsa** [alexherbo2/connect.kak#6]
I was installing `connect.kak` following the instructions and I was a bit shocked that it didn't work. After some internet browsing, I checked in [arch wiki](https://wiki.archlinux.org/index.php/Desktop_entries) that it is mandatory for `.desktop` files to contain a `Type` field. After adding the line `Type=Application` everything started working appropriately. I'm using Ubuntu 18.04.

**Comment by alexherbo2** [comment]
Thanks for your time to find the fix.

**Comment by useredsa** [comment]
No, the fix was only one line! Thank YOU for developing this tool.
